# Use the official Docker Library Drupal image
# It contains Apache and PHP.
# Both Apache and PHP are already setup for Drupal sites.
FROM drupal

# Remove the provided Drupal files
RUN rm -rf /var/www/html/*
