version: "3"

services:
  drupal:
    image: drupal
    ports:
      - "81:80"
    depends_on:
      - db

#   db:
#     image: mariadb:10.3
#     environment:
#       MYSQL_ROOT_PASSWORD: pass123
#       MYSQL_DATABASE: drupal
#     volumes:
#       - db_data:/var/lib/mysql
#
# volumes:
#   db_data:
